Added dbContext
PGBSNH19/spacepark-grupp-1-spacepark pull request #14
Opened 2020-09-15 14:39 UTC by kaptenen

2020-09-15 16:21 UTC, Gerglamesh requested changes
Lite småpill, har lagt kommentarer i koden.

2020-09-15 16:21 UTC, Gerglamesh commented on SpaceParkAPI/SpaceParkAPI/Db-Context/SpaceParkContext.cs
> +        public virtual DbSet<ParkingSpaceModel> ParkingSpaces { get; set; }
Här får vi build error, tror vi behöver se till att "ParkingSpace" heter "ParkingSpaceModel" och att namespacet är korrekt.

2020-09-15 16:21 UTC, Gerglamesh commented on SpaceParkAPI/SpaceParkAPI/Db-Context/SpaceParkContext.cs
> +        public virtual DbSet<PersonModel> PersonModels { get; set; }
På dessa två bör vi kanske se över konventionen så att det antingen heter "model" på slutet eller inte.

2020-09-16 11:35 UTC, simbasang approved these changes

2020-09-16 11:37 UTC, Gerglamesh approved these changes

2020-09-16 11:37 UTC, merged